// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/attribution.dart';
import 'api/install.dart';
import 'api/logging.dart';
import 'api/preview.dart';
import 'api/satellites.dart';
import 'api/solver.dart';
import 'api/types.dart';
import 'api/wcs.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';
import 'lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UniAnnotatorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotatorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UniCalibrationPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibrationPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UniSolverPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UniSolverPoolPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPoolPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  UniAnnotator
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    dynamic raw,
  );

  @protected
  UniCalibration
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    dynamic raw,
  );

  @protected
  UniSolver
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    dynamic raw,
  );

  @protected
  UniSolverPool
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    dynamic raw,
  );

  @protected
  UniAnnotator
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    dynamic raw,
  );

  @protected
  UniCalibration
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    dynamic raw,
  );

  @protected
  UniSolver
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    dynamic raw,
  );

  @protected
  UniSolverPool
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    dynamic raw,
  );

  @protected
  UniAnnotator
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    dynamic raw,
  );

  @protected
  UniCalibration
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    dynamic raw,
  );

  @protected
  UniSolver
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    dynamic raw,
  );

  @protected
  UniSolverPool
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogEventDto> dco_decode_StreamSink_log_event_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnnotateOptionsDto dco_decode_annotate_options_dto(dynamic raw);

  @protected
  AnnotationsDto dco_decode_annotations_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BoundaryAnnotationDto dco_decode_boundary_annotation_dto(dynamic raw);

  @protected
  AnnotateOptionsDto dco_decode_box_autoadd_annotate_options_dto(dynamic raw);

  @protected
  CalibModelDto dco_decode_box_autoadd_calib_model_dto(dynamic raw);

  @protected
  CameraParamsDto dco_decode_box_autoadd_camera_params_dto(dynamic raw);

  @protected
  ConstellationArtDto dco_decode_box_autoadd_constellation_art_dto(dynamic raw);

  @protected
  ConstellationNameDto dco_decode_box_autoadd_constellation_name_dto(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FrameDto dco_decode_box_autoadd_frame_dto(dynamic raw);

  @protected
  GridLabelDto dco_decode_box_autoadd_grid_label_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ObserverDto dco_decode_box_autoadd_observer_dto(dynamic raw);

  @protected
  SolveOptionsDto dco_decode_box_autoadd_solve_options_dto(dynamic raw);

  @protected
  SolvedGeometryDto dco_decode_box_autoadd_solved_geometry_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ViewportDto dco_decode_box_autoadd_viewport_dto(dynamic raw);

  @protected
  WcsDto dco_decode_box_autoadd_wcs_dto(dynamic raw);

  @protected
  CalibModelDto dco_decode_calib_model_dto(dynamic raw);

  @protected
  CalibrationReportDto dco_decode_calibration_report_dto(dynamic raw);

  @protected
  CameraParamsDto dco_decode_camera_params_dto(dynamic raw);

  @protected
  CentroidDto dco_decode_centroid_dto(dynamic raw);

  @protected
  ConstellationAnnotationDto dco_decode_constellation_annotation_dto(
    dynamic raw,
  );

  @protected
  ConstellationArtDto dco_decode_constellation_art_dto(dynamic raw);

  @protected
  ConstellationNameDto dco_decode_constellation_name_dto(dynamic raw);

  @protected
  DataAttributionDto dco_decode_data_attribution_dto(dynamic raw);

  @protected
  DbPropertiesDto dco_decode_db_properties_dto(dynamic raw);

  @protected
  DistortionDto dco_decode_distortion_dto(dynamic raw);

  @protected
  DsoAnnotationDto dco_decode_dso_annotation_dto(dynamic raw);

  @protected
  DsoKindDto dco_decode_dso_kind_dto(dynamic raw);

  @protected
  DsoOutlineDto dco_decode_dso_outline_dto(dynamic raw);

  @protected
  ExtractionProfileDto dco_decode_extraction_profile_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  F32Array4 dco_decode_f_32_array_4(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  F64Array4 dco_decode_f_64_array_4(dynamic raw);

  @protected
  FovAttemptDto dco_decode_fov_attempt_dto(dynamic raw);

  @protected
  FovPresetDto dco_decode_fov_preset_dto(dynamic raw);

  @protected
  FrameDto dco_decode_frame_dto(dynamic raw);

  @protected
  GridEdgeDto dco_decode_grid_edge_dto(dynamic raw);

  @protected
  GridKindDto dco_decode_grid_kind_dto(dynamic raw);

  @protected
  GridLabelDto dco_decode_grid_label_dto(dynamic raw);

  @protected
  GridLineDto dco_decode_grid_line_dto(dynamic raw);

  @protected
  GridSystemDto dco_decode_grid_system_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImagePreviewDto dco_decode_image_preview_dto(dynamic raw);

  @protected
  LadderOutcomeDto dco_decode_ladder_outcome_dto(dynamic raw);

  @protected
  LayerAvailabilityDto dco_decode_layer_availability_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BoundaryAnnotationDto> dco_decode_list_boundary_annotation_dto(
    dynamic raw,
  );

  @protected
  List<CentroidDto> dco_decode_list_centroid_dto(dynamic raw);

  @protected
  List<ConstellationAnnotationDto> dco_decode_list_constellation_annotation_dto(
    dynamic raw,
  );

  @protected
  List<DataAttributionDto> dco_decode_list_data_attribution_dto(dynamic raw);

  @protected
  List<DsoAnnotationDto> dco_decode_list_dso_annotation_dto(dynamic raw);

  @protected
  List<DsoOutlineDto> dco_decode_list_dso_outline_dto(dynamic raw);

  @protected
  List<FovAttemptDto> dco_decode_list_fov_attempt_dto(dynamic raw);

  @protected
  List<FovPresetDto> dco_decode_list_fov_preset_dto(dynamic raw);

  @protected
  List<GridLineDto> dco_decode_list_grid_line_dto(dynamic raw);

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw);

  @protected
  List<MatchDto> dco_decode_list_match_dto(dynamic raw);

  @protected
  List<NamedStarAnnotationDto> dco_decode_list_named_star_annotation_dto(
    dynamic raw,
  );

  @protected
  List<OutlineContourDto> dco_decode_list_outline_contour_dto(dynamic raw);

  @protected
  List<PoolAttemptDto> dco_decode_list_pool_attempt_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SatelliteAnnotationDto> dco_decode_list_satellite_annotation_dto(
    dynamic raw,
  );

  @protected
  List<SatellitePosDto> dco_decode_list_satellite_pos_dto(dynamic raw);

  @protected
  List<SolarAnnotationDto> dco_decode_list_solar_annotation_dto(dynamic raw);

  @protected
  List<StarAnnotationDto> dco_decode_list_star_annotation_dto(dynamic raw);

  @protected
  List<TierInfoDto> dco_decode_list_tier_info_dto(dynamic raw);

  @protected
  LogEventDto dco_decode_log_event_dto(dynamic raw);

  @protected
  MatchDto dco_decode_match_dto(dynamic raw);

  @protected
  NamedStarAnnotationDto dco_decode_named_star_annotation_dto(dynamic raw);

  @protected
  ObserverDto dco_decode_observer_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CameraParamsDto? dco_decode_opt_box_autoadd_camera_params_dto(dynamic raw);

  @protected
  ConstellationArtDto? dco_decode_opt_box_autoadd_constellation_art_dto(
    dynamic raw,
  );

  @protected
  ConstellationNameDto? dco_decode_opt_box_autoadd_constellation_name_dto(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GridLabelDto? dco_decode_opt_box_autoadd_grid_label_dto(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ObserverDto? dco_decode_opt_box_autoadd_observer_dto(dynamic raw);

  @protected
  SolvedGeometryDto? dco_decode_opt_box_autoadd_solved_geometry_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ViewportDto? dco_decode_opt_box_autoadd_viewport_dto(dynamic raw);

  @protected
  F32Array4? dco_decode_opt_f_32_array_4(dynamic raw);

  @protected
  OutlineContourDto dco_decode_outline_contour_dto(dynamic raw);

  @protected
  PixelKindDto dco_decode_pixel_kind_dto(dynamic raw);

  @protected
  PoolAttemptDto dco_decode_pool_attempt_dto(dynamic raw);

  @protected
  PoolOutcomeDto dco_decode_pool_outcome_dto(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SatelliteAnnotationDto dco_decode_satellite_annotation_dto(dynamic raw);

  @protected
  SatellitePosDto dco_decode_satellite_pos_dto(dynamic raw);

  @protected
  SolarAnnotationDto dco_decode_solar_annotation_dto(dynamic raw);

  @protected
  SolveOptionsDto dco_decode_solve_options_dto(dynamic raw);

  @protected
  SolveOutcomeDto dco_decode_solve_outcome_dto(dynamic raw);

  @protected
  SolveStatusDto dco_decode_solve_status_dto(dynamic raw);

  @protected
  SolvedGeometryDto dco_decode_solved_geometry_dto(dynamic raw);

  @protected
  StarAnnotationDto dco_decode_star_annotation_dto(dynamic raw);

  @protected
  TierInfoDto dco_decode_tier_info_dto(dynamic raw);

  @protected
  TimingDto dco_decode_timing_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ViewportDto dco_decode_viewport_dto(dynamic raw);

  @protected
  WcsDto dco_decode_wcs_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  UniAnnotator
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    SseDeserializer deserializer,
  );

  @protected
  UniCalibration
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    SseDeserializer deserializer,
  );

  @protected
  UniSolver
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    SseDeserializer deserializer,
  );

  @protected
  UniSolverPool
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    SseDeserializer deserializer,
  );

  @protected
  UniAnnotator
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    SseDeserializer deserializer,
  );

  @protected
  UniCalibration
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    SseDeserializer deserializer,
  );

  @protected
  UniSolver
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    SseDeserializer deserializer,
  );

  @protected
  UniSolverPool
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    SseDeserializer deserializer,
  );

  @protected
  UniAnnotator
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    SseDeserializer deserializer,
  );

  @protected
  UniCalibration
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    SseDeserializer deserializer,
  );

  @protected
  UniSolver
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    SseDeserializer deserializer,
  );

  @protected
  UniSolverPool
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEventDto> sse_decode_StreamSink_log_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnnotateOptionsDto sse_decode_annotate_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  AnnotationsDto sse_decode_annotations_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BoundaryAnnotationDto sse_decode_boundary_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  AnnotateOptionsDto sse_decode_box_autoadd_annotate_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  CalibModelDto sse_decode_box_autoadd_calib_model_dto(
    SseDeserializer deserializer,
  );

  @protected
  CameraParamsDto sse_decode_box_autoadd_camera_params_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConstellationArtDto sse_decode_box_autoadd_constellation_art_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConstellationNameDto sse_decode_box_autoadd_constellation_name_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrameDto sse_decode_box_autoadd_frame_dto(SseDeserializer deserializer);

  @protected
  GridLabelDto sse_decode_box_autoadd_grid_label_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ObserverDto sse_decode_box_autoadd_observer_dto(SseDeserializer deserializer);

  @protected
  SolveOptionsDto sse_decode_box_autoadd_solve_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  SolvedGeometryDto sse_decode_box_autoadd_solved_geometry_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ViewportDto sse_decode_box_autoadd_viewport_dto(SseDeserializer deserializer);

  @protected
  WcsDto sse_decode_box_autoadd_wcs_dto(SseDeserializer deserializer);

  @protected
  CalibModelDto sse_decode_calib_model_dto(SseDeserializer deserializer);

  @protected
  CalibrationReportDto sse_decode_calibration_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  CameraParamsDto sse_decode_camera_params_dto(SseDeserializer deserializer);

  @protected
  CentroidDto sse_decode_centroid_dto(SseDeserializer deserializer);

  @protected
  ConstellationAnnotationDto sse_decode_constellation_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConstellationArtDto sse_decode_constellation_art_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConstellationNameDto sse_decode_constellation_name_dto(
    SseDeserializer deserializer,
  );

  @protected
  DataAttributionDto sse_decode_data_attribution_dto(
    SseDeserializer deserializer,
  );

  @protected
  DbPropertiesDto sse_decode_db_properties_dto(SseDeserializer deserializer);

  @protected
  DistortionDto sse_decode_distortion_dto(SseDeserializer deserializer);

  @protected
  DsoAnnotationDto sse_decode_dso_annotation_dto(SseDeserializer deserializer);

  @protected
  DsoKindDto sse_decode_dso_kind_dto(SseDeserializer deserializer);

  @protected
  DsoOutlineDto sse_decode_dso_outline_dto(SseDeserializer deserializer);

  @protected
  ExtractionProfileDto sse_decode_extraction_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  F32Array4 sse_decode_f_32_array_4(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  F64Array4 sse_decode_f_64_array_4(SseDeserializer deserializer);

  @protected
  FovAttemptDto sse_decode_fov_attempt_dto(SseDeserializer deserializer);

  @protected
  FovPresetDto sse_decode_fov_preset_dto(SseDeserializer deserializer);

  @protected
  FrameDto sse_decode_frame_dto(SseDeserializer deserializer);

  @protected
  GridEdgeDto sse_decode_grid_edge_dto(SseDeserializer deserializer);

  @protected
  GridKindDto sse_decode_grid_kind_dto(SseDeserializer deserializer);

  @protected
  GridLabelDto sse_decode_grid_label_dto(SseDeserializer deserializer);

  @protected
  GridLineDto sse_decode_grid_line_dto(SseDeserializer deserializer);

  @protected
  GridSystemDto sse_decode_grid_system_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImagePreviewDto sse_decode_image_preview_dto(SseDeserializer deserializer);

  @protected
  LadderOutcomeDto sse_decode_ladder_outcome_dto(SseDeserializer deserializer);

  @protected
  LayerAvailabilityDto sse_decode_layer_availability_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BoundaryAnnotationDto> sse_decode_list_boundary_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CentroidDto> sse_decode_list_centroid_dto(SseDeserializer deserializer);

  @protected
  List<ConstellationAnnotationDto> sse_decode_list_constellation_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DataAttributionDto> sse_decode_list_data_attribution_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DsoAnnotationDto> sse_decode_list_dso_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DsoOutlineDto> sse_decode_list_dso_outline_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FovAttemptDto> sse_decode_list_fov_attempt_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FovPresetDto> sse_decode_list_fov_preset_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GridLineDto> sse_decode_list_grid_line_dto(SseDeserializer deserializer);

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MatchDto> sse_decode_list_match_dto(SseDeserializer deserializer);

  @protected
  List<NamedStarAnnotationDto> sse_decode_list_named_star_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<OutlineContourDto> sse_decode_list_outline_contour_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PoolAttemptDto> sse_decode_list_pool_attempt_dto(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SatelliteAnnotationDto> sse_decode_list_satellite_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SatellitePosDto> sse_decode_list_satellite_pos_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SolarAnnotationDto> sse_decode_list_solar_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<StarAnnotationDto> sse_decode_list_star_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TierInfoDto> sse_decode_list_tier_info_dto(SseDeserializer deserializer);

  @protected
  LogEventDto sse_decode_log_event_dto(SseDeserializer deserializer);

  @protected
  MatchDto sse_decode_match_dto(SseDeserializer deserializer);

  @protected
  NamedStarAnnotationDto sse_decode_named_star_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ObserverDto sse_decode_observer_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CameraParamsDto? sse_decode_opt_box_autoadd_camera_params_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConstellationArtDto? sse_decode_opt_box_autoadd_constellation_art_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConstellationNameDto? sse_decode_opt_box_autoadd_constellation_name_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GridLabelDto? sse_decode_opt_box_autoadd_grid_label_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ObserverDto? sse_decode_opt_box_autoadd_observer_dto(
    SseDeserializer deserializer,
  );

  @protected
  SolvedGeometryDto? sse_decode_opt_box_autoadd_solved_geometry_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ViewportDto? sse_decode_opt_box_autoadd_viewport_dto(
    SseDeserializer deserializer,
  );

  @protected
  F32Array4? sse_decode_opt_f_32_array_4(SseDeserializer deserializer);

  @protected
  OutlineContourDto sse_decode_outline_contour_dto(
    SseDeserializer deserializer,
  );

  @protected
  PixelKindDto sse_decode_pixel_kind_dto(SseDeserializer deserializer);

  @protected
  PoolAttemptDto sse_decode_pool_attempt_dto(SseDeserializer deserializer);

  @protected
  PoolOutcomeDto sse_decode_pool_outcome_dto(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SatelliteAnnotationDto sse_decode_satellite_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  SatellitePosDto sse_decode_satellite_pos_dto(SseDeserializer deserializer);

  @protected
  SolarAnnotationDto sse_decode_solar_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  SolveOptionsDto sse_decode_solve_options_dto(SseDeserializer deserializer);

  @protected
  SolveOutcomeDto sse_decode_solve_outcome_dto(SseDeserializer deserializer);

  @protected
  SolveStatusDto sse_decode_solve_status_dto(SseDeserializer deserializer);

  @protected
  SolvedGeometryDto sse_decode_solved_geometry_dto(
    SseDeserializer deserializer,
  );

  @protected
  StarAnnotationDto sse_decode_star_annotation_dto(
    SseDeserializer deserializer,
  );

  @protected
  TierInfoDto sse_decode_tier_info_dto(SseDeserializer deserializer);

  @protected
  TimingDto sse_decode_timing_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ViewportDto sse_decode_viewport_dto(SseDeserializer deserializer);

  @protected
  WcsDto sse_decode_wcs_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    UniAnnotator self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    UniCalibration self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    UniSolver self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    UniSolverPool self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    UniAnnotator self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    UniCalibration self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    UniSolver self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    UniSolverPool self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    UniAnnotator self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    UniCalibration self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    UniSolver self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    UniSolverPool self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_event_dto_Sse(
    RustStreamSink<LogEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_annotate_options_dto(
    AnnotateOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_annotations_dto(
    AnnotationsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_boundary_annotation_dto(
    BoundaryAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_annotate_options_dto(
    AnnotateOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_calib_model_dto(
    CalibModelDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_camera_params_dto(
    CameraParamsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_constellation_art_dto(
    ConstellationArtDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_constellation_name_dto(
    ConstellationNameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frame_dto(
    FrameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_grid_label_dto(
    GridLabelDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_observer_dto(
    ObserverDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_solve_options_dto(
    SolveOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_solved_geometry_dto(
    SolvedGeometryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_viewport_dto(
    ViewportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wcs_dto(WcsDto self, SseSerializer serializer);

  @protected
  void sse_encode_calib_model_dto(CalibModelDto self, SseSerializer serializer);

  @protected
  void sse_encode_calibration_report_dto(
    CalibrationReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_camera_params_dto(
    CameraParamsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_centroid_dto(CentroidDto self, SseSerializer serializer);

  @protected
  void sse_encode_constellation_annotation_dto(
    ConstellationAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_constellation_art_dto(
    ConstellationArtDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_constellation_name_dto(
    ConstellationNameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_data_attribution_dto(
    DataAttributionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_properties_dto(
    DbPropertiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_distortion_dto(DistortionDto self, SseSerializer serializer);

  @protected
  void sse_encode_dso_annotation_dto(
    DsoAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dso_kind_dto(DsoKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_dso_outline_dto(DsoOutlineDto self, SseSerializer serializer);

  @protected
  void sse_encode_extraction_profile_dto(
    ExtractionProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_32_array_4(F32Array4 self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64_array_4(F64Array4 self, SseSerializer serializer);

  @protected
  void sse_encode_fov_attempt_dto(FovAttemptDto self, SseSerializer serializer);

  @protected
  void sse_encode_fov_preset_dto(FovPresetDto self, SseSerializer serializer);

  @protected
  void sse_encode_frame_dto(FrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_grid_edge_dto(GridEdgeDto self, SseSerializer serializer);

  @protected
  void sse_encode_grid_kind_dto(GridKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_grid_label_dto(GridLabelDto self, SseSerializer serializer);

  @protected
  void sse_encode_grid_line_dto(GridLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_grid_system_dto(GridSystemDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_preview_dto(
    ImagePreviewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ladder_outcome_dto(
    LadderOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_layer_availability_dto(
    LayerAvailabilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_boundary_annotation_dto(
    List<BoundaryAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_centroid_dto(
    List<CentroidDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_constellation_annotation_dto(
    List<ConstellationAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_data_attribution_dto(
    List<DataAttributionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dso_annotation_dto(
    List<DsoAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dso_outline_dto(
    List<DsoOutlineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fov_attempt_dto(
    List<FovAttemptDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fov_preset_dto(
    List<FovPresetDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_grid_line_dto(
    List<GridLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_f_64_strict(
    List<Float64List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_match_dto(List<MatchDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_named_star_annotation_dto(
    List<NamedStarAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_outline_contour_dto(
    List<OutlineContourDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pool_attempt_dto(
    List<PoolAttemptDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_satellite_annotation_dto(
    List<SatelliteAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_satellite_pos_dto(
    List<SatellitePosDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_solar_annotation_dto(
    List<SolarAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_star_annotation_dto(
    List<StarAnnotationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tier_info_dto(
    List<TierInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_event_dto(LogEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_match_dto(MatchDto self, SseSerializer serializer);

  @protected
  void sse_encode_named_star_annotation_dto(
    NamedStarAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_observer_dto(ObserverDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_camera_params_dto(
    CameraParamsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_constellation_art_dto(
    ConstellationArtDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_constellation_name_dto(
    ConstellationNameDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_grid_label_dto(
    GridLabelDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_observer_dto(
    ObserverDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_solved_geometry_dto(
    SolvedGeometryDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_viewport_dto(
    ViewportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_f_32_array_4(F32Array4? self, SseSerializer serializer);

  @protected
  void sse_encode_outline_contour_dto(
    OutlineContourDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pixel_kind_dto(PixelKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_pool_attempt_dto(
    PoolAttemptDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pool_outcome_dto(
    PoolOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_satellite_annotation_dto(
    SatelliteAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_satellite_pos_dto(
    SatellitePosDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_solar_annotation_dto(
    SolarAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_solve_options_dto(
    SolveOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_solve_outcome_dto(
    SolveOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_solve_status_dto(
    SolveStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_solved_geometry_dto(
    SolvedGeometryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_star_annotation_dto(
    StarAnnotationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tier_info_dto(TierInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_timing_dto(TimingDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_viewport_dto(ViewportDto self, SseSerializer serializer);

  @protected
  void sse_encode_wcs_dto(WcsDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotatorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotatorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotatorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotator =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniAnnotatorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibrationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibrationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibrationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibration =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniCalibrationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolver =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPoolPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPoolPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPoolPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_unisolver_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPool =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUniSolverPoolPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
