//! Low-precision solar-system ephemeris for annotation.
//!
//! Target accuracy for annotation markers: ≲ 0.2° for planets, ≲ 0.3° for the moon.
//!
//! - Planets: JPL approximate Keplerian elements (Standish 1992, 1800–2050 AD) and
//!   Kepler's equation, made geocentric with a first-order light-time iteration;
//! - Sun: from Earth's elements;
//! - Moon: truncated main terms of Meeus chapter 47.
//!
//! Test anchors are generated by astropy (builtin ephemeris), not copied by hand.
use std::f64::consts::PI;

#[derive(Debug, Clone)]
pub struct SolarBody {
    pub name_en: &'static str,
    pub name_zh: &'static str,
    /// Geocentric apparent direction (no nutation or aberration: < 0.01°, irrelevant for annotation)
    pub ra_deg: f64,
    pub dec_deg: f64,
    /// Apparent angular radius (degrees); None for planets too small to resolve (draw a fixed marker)
    pub angular_radius_deg: Option<f64>,
}

const OBLIQUITY_J2000: f64 = 23.439_291_1;

/// Observer location (shared by the moon's parallax correction and the satellite layer).
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Observer {
    pub lat_deg: f64,
    pub lon_deg: f64,
    pub alt_m: f64,
}

impl Observer {
    /// Out-of-range values are rejected, not clamped: the correction is sensitive to the
    /// latitude sign, and the wrong hemisphere is off by 2°.
    pub fn validate(&self) -> crate::Result<()> {
        let ok = (-90.0..=90.0).contains(&self.lat_deg)
            && (-180.0..=360.0).contains(&self.lon_deg)
            && (-500.0..=20_000.0).contains(&self.alt_m)
            && self.lat_deg.is_finite()
            && self.lon_deg.is_finite()
            && self.alt_m.is_finite();
        ok.then_some(()).ok_or_else(|| {
            crate::CoreError::InvalidInput(format!(
                "observer out of range: lat {} lon {} alt {}",
                self.lat_deg, self.lon_deg, self.alt_m
            ))
        })
    }
}

/// Greenwich mean sidereal time in degrees (Meeus 12.4)
pub(crate) fn gmst_deg(unix_ms: i64) -> f64 {
    let d = crate::days_since_j2000(unix_ms);
    let t = d / 36_525.0;
    (280.460_618_37 + 360.985_647_366_29 * d + 0.000_387_933 * t * t).rem_euclid(360.0)
}

/// Observer position in the equatorial inertial frame (km, spherical Earth).
///
/// This uses the **true equator of date** from GMST while body positions are J2000;
/// the ~0.4° of accumulated precession only rotates this ≤ 6378 km vector, changing
/// the apparent position by ≤ |parallax| × sin(0.4°) ≈ 0.007° (moon parallax ≤ ~1°),
/// far below annotation accuracy. The satellite layer makes the same approximation.
pub(crate) fn observer_eci(obs: &Observer, unix_ms: i64) -> [f64; 3] {
    const RE_KM: f64 = 6378.137;
    let lat = obs.lat_deg.to_radians();
    let r = (RE_KM + obs.alt_m / 1000.0) * lat.cos();
    let z = (RE_KM + obs.alt_m / 1000.0) * lat.sin();
    let lst = (gmst_deg(unix_ms) + obs.lon_deg).to_radians();
    [r * lst.cos(), r * lst.sin(), z]
}

/// JPL approximate elements (J2000 epoch, rates per Julian century):
/// [a (AU), e, I (deg), L (deg), long.peri (deg), long.node (deg)] plus rates in the same order.
/// Order: Mercury..Neptune plus the Earth–Moon barycenter (Earth).
#[rustfmt::skip]
const ELEMENTS: [(&str, &str, [f64; 6], [f64; 6]); 9] = [
    ("mercury", "水星", [0.387_098_43, 0.205_635_93, 7.004_979_02, 252.250_324_35, 77.457_796_28, 48.330_766_04],
                        [0.000_000_37, 0.000_019_06, -0.005_946_49, 149_472.674_113_91, 0.160_474_70, -0.125_341_08]),
    ("venus",   "金星", [0.723_335_66, 0.006_776_72, 3.394_676_05, 181.979_099_50, 131.602_467_18, 76.679_843_06],
                        [0.000_003_90, -0.000_041_07, -0.000_788_90, 58_517.815_387_29, 0.002_684_60, -0.278_008_00]),
    ("earth",   "地球", [1.000_002_61, 0.016_711_23, -0.000_015_31, 100.464_571_66, 102.937_681_93, 0.0],
                        [0.000_005_62, -0.000_043_92, -0.012_946_68, 35_999.372_449_81, 0.323_273_64, 0.0]),
    ("mars",    "火星", [1.523_710_34, 0.093_393_41, 1.849_691_42, -4.553_432_05, -23.943_629_59, 49.559_539_09],
                        [0.000_018_47, 0.000_078_82, -0.008_131_31, 19_140.302_684_99, 0.443_810_50, -0.292_573_43]),
    ("jupiter", "木星", [5.202_887_00, 0.048_386_24, 1.304_396_95, 34.396_441_00, 14.728_479_83, 100.473_909_09],
                        [-0.000_116_07, -0.000_132_53, -0.001_836_14, 3_034.746_128_50, 0.213_252_09, 0.204_691_06]),
    ("saturn",  "土星", [9.536_675_94, 0.053_862_10, 2.485_991_87, 49.954_244_23, 92.598_878_31, 113.662_424_48],
                        [-0.001_250_60, -0.000_506_91, 0.001_936_09, 1_222.493_622_01, -0.418_979_16, -0.288_679_43]),
    ("uranus",  "天王星", [19.189_164_64, 0.047_257_44, 0.772_638_31, 313.238_104_51, 170.954_275_98, 74.016_925_46],
                        [-0.001_965_18, -0.000_044_397, -0.002_425_39, 428.481_202_79, 0.408_053_81, 0.042_405_89]),
    ("neptune", "海王星", [30.069_923_43, 0.008_590_48, 1.770_043_52, -55.120_029_70, 44.964_762_59, 131.784_225_74],
                        [0.000_262_91, 0.000_050_105, 0.000_353_72, 218.459_455_09, -0.322_414_64, -0.005_083_64]),
    ("pluto",   "冥王星", [39.482_116_75, 0.248_827_30, 17.140_013_06, 238.929_038_33, 224.068_916_29, 110.303_936_84],
                        [-0.000_318_96, 0.000_051_70, 0.000_045_39, 145.207_805_15, -0.041_062_44, -0.011_836_07]),
];

fn wrap360(x: f64) -> f64 {
    x.rem_euclid(360.0)
}

/// Kepler's equation E − e·sinE = M (degrees in and out)
fn kepler(m_deg: f64, e: f64) -> f64 {
    let m = wrap360(m_deg).to_radians();
    let mut ea = if e < 0.8 { m } else { PI };
    for _ in 0..12 {
        let d = ea - e * ea.sin() - m;
        ea -= d / (1.0 - e * ea.cos());
    }
    ea
}

/// Heliocentric ecliptic J2000 rectangular coordinates of a planet (AU)
fn heliocentric(idx: usize, t_centuries: f64) -> [f64; 3] {
    let (_, _, e0, dr) = ELEMENTS[idx];
    let a = e0[0] + dr[0] * t_centuries;
    let ecc = e0[1] + dr[1] * t_centuries;
    let inc = (e0[2] + dr[2] * t_centuries).to_radians();
    let l = e0[3] + dr[3] * t_centuries;
    let peri = e0[4] + dr[4] * t_centuries;
    let node = e0[5] + dr[5] * t_centuries;

    let m = l - peri;
    let omega = (peri - node).to_radians();
    let node = node.to_radians();
    let ea = kepler(m, ecc);
    let xp = a * (ea.cos() - ecc);
    let yp = a * (1.0 - ecc * ecc).sqrt() * ea.sin();

    let (so, co) = (omega.sin(), omega.cos());
    let (sn, cn) = (node.sin(), node.cos());
    let (si, ci) = (inc.sin(), inc.cos());
    [
        (co * cn - so * sn * ci) * xp + (-so * cn - co * sn * ci) * yp,
        (co * sn + so * cn * ci) * xp + (-so * sn + co * cn * ci) * yp,
        (so * si) * xp + (co * si) * yp,
    ]
}

fn ecl_to_radec(x: f64, y: f64, z: f64) -> (f64, f64) {
    let eps = OBLIQUITY_J2000.to_radians();
    let (se, ce) = (eps.sin(), eps.cos());
    let xe = x;
    let ye = y * ce - z * se;
    let ze = y * se + z * ce;
    let ra = ye.atan2(xe).to_degrees().rem_euclid(360.0);
    let dec = (ze / (xe * xe + ye * ye + ze * ze).sqrt())
        .asin()
        .to_degrees();
    (ra, dec)
}

/// Moon position from Meeus chapter 47 (truncated main terms, ~0.05°)
fn moon_radec(t: f64) -> (f64, f64, f64) {
    let lp = wrap360(218.3164477 + 481267.88123421 * t - 0.0015786 * t * t);
    let d = wrap360(297.8501921 + 445267.1114034 * t - 0.0018819 * t * t);
    let m = wrap360(357.5291092 + 35999.0502909 * t - 0.0001536 * t * t);
    let mp = wrap360(134.9633964 + 477198.8675055 * t + 0.0087414 * t * t);
    let f = wrap360(93.2720950 + 483202.0175233 * t - 0.0036539 * t * t);
    let e = 1.0 - 0.002516 * t - 0.0000074 * t * t; // Meeus E: eccentricity correction for M terms
    let r = |x: f64| x.to_radians();

    // Main longitude terms (1e-6 deg) and distance terms (1e-3 km), Meeus table 47.a, truncated
    let sl = 6_288_774.0 * r(mp).sin()
        + 1_274_027.0 * r(2.0 * d - mp).sin()
        + 658_314.0 * r(2.0 * d).sin()
        + 213_618.0 * r(2.0 * mp).sin()
        - 185_116.0 * e * r(m).sin()
        - 114_332.0 * r(2.0 * f).sin()
        + 58_793.0 * r(2.0 * d - 2.0 * mp).sin()
        + 57_066.0 * e * r(2.0 * d - m - mp).sin()
        + 53_322.0 * r(2.0 * d + mp).sin()
        + 45_758.0 * e * r(2.0 * d - m).sin()
        - 40_923.0 * e * r(m - mp).sin()
        - 34_720.0 * r(d).sin()
        - 30_383.0 * e * r(m + mp).sin()
        + 15_327.0 * r(2.0 * d - 2.0 * f).sin()
        - 12_528.0 * r(mp + 2.0 * f).sin()
        + 10_980.0 * r(mp - 2.0 * f).sin()
        + 10_675.0 * r(4.0 * d - mp).sin()
        + 10_034.0 * r(3.0 * mp).sin()
        + 8_548.0 * r(4.0 * d - 2.0 * mp).sin()
        - 7_888.0 * e * r(2.0 * d + m - mp).sin()
        - 6_766.0 * e * r(2.0 * d + m).sin()
        - 5_163.0 * r(d - mp).sin()
        + 4_987.0 * e * r(d + m).sin()
        + 4_036.0 * e * r(2.0 * d - m + mp).sin();
    let sr = -20_905_355.0 * r(mp).cos()
        - 3_699_111.0 * r(2.0 * d - mp).cos()
        - 2_955_968.0 * r(2.0 * d).cos()
        - 569_925.0 * r(2.0 * mp).cos()
        + 48_888.0 * r(m).cos()
        - 3_149.0 * r(2.0 * f).cos()
        + 246_158.0 * r(2.0 * d - 2.0 * mp).cos()
        - 152_138.0 * r(2.0 * d - m - mp).cos()
        - 170_733.0 * r(2.0 * d + mp).cos()
        - 204_586.0 * r(2.0 * d - m).cos();
    // Main latitude terms (1e-6 deg)
    let sb = 5_128_122.0 * r(f).sin()
        + 280_602.0 * r(mp + f).sin()
        + 277_693.0 * r(mp - f).sin()
        + 173_237.0 * r(2.0 * d - f).sin()
        + 55_413.0 * r(2.0 * d - mp + f).sin()
        + 46_271.0 * r(2.0 * d - mp - f).sin()
        + 32_573.0 * r(2.0 * d + f).sin()
        + 17_198.0 * r(2.0 * mp + f).sin();

    // Meeus gives the longitude for the equinox of date, while planets and the output are
    // J2000: undo the accumulated precession (1.396971°/century). Latitude is unaffected.
    let lon = lp + sl / 1_000_000.0 - (1.396_971 * t + 0.000_308_6 * t * t);
    let lat = sb / 1_000_000.0;
    let dist_km = 385_000.56 + sr / 1000.0;
    let (lr, br) = (lon.to_radians(), lat.to_radians());
    let (ra, dec) = ecl_to_radec(br.cos() * lr.cos(), br.cos() * lr.sin(), br.sin());
    (ra, dec, dist_km)
}

/// Unix ms → Julian centuries since J2000 (UTC ≈ TT is enough at this accuracy)
fn centuries(unix_ms: i64) -> f64 {
    crate::days_since_j2000(unix_ms) / 36_525.0
}

/// **Geocentric** apparent positions of all annotated solar-system bodies (first-order light time).
pub fn solar_system_positions(unix_ms: i64) -> Vec<SolarBody> {
    solar_system_positions_at(unix_ms, None)
}

/// As above, with a topocentric parallax correction for the **moon** when an observer is given.
///
/// Only the moon, because parallax ≈ Earth radius / distance: 0.8–1.0° for the moon (two
/// lunar diameters, visibly wrong), 0.0024° for the sun, ≤ 0.0005° for planets, which is
/// far below annotation accuracy.
pub fn solar_system_positions_at(unix_ms: i64, observer: Option<&Observer>) -> Vec<SolarBody> {
    let t = centuries(unix_ms);
    let earth = heliocentric(2, t);
    let mut out = Vec::new();

    // Sun: the negated Earth position
    {
        let (ra, dec) = ecl_to_radec(-earth[0], -earth[1], -earth[2]);
        out.push(SolarBody {
            name_en: "Sun",
            name_zh: "太阳",
            ra_deg: ra,
            dec_deg: dec,
            angular_radius_deg: Some(0.267),
        });
    }
    // Moon (topocentric correction here)
    {
        let (mut ra, mut dec, mut dist_km) = moon_radec(t);
        if let Some(obs) = observer {
            let (r, d) = (ra.to_radians(), dec.to_radians());
            let geo = [
                dist_km * d.cos() * r.cos(),
                dist_km * d.cos() * r.sin(),
                dist_km * d.sin(),
            ];
            let o = observer_eci(obs, unix_ms);
            let topo = [geo[0] - o[0], geo[1] - o[1], geo[2] - o[2]];
            dist_km = (topo[0] * topo[0] + topo[1] * topo[1] + topo[2] * topo[2]).sqrt();
            ra = topo[1].atan2(topo[0]).to_degrees().rem_euclid(360.0);
            dec = (topo[2] / dist_km).asin().to_degrees();
        }
        out.push(SolarBody {
            name_en: "Moon",
            name_zh: "月亮",
            ra_deg: ra,
            dec_deg: dec,
            // The apparent radius changes by ±1.7% with topocentric distance; update it too
            angular_radius_deg: Some((1738.0 / dist_km).asin().to_degrees()),
        });
    }
    // Planets (skipping Earth): first-order light time: geometric distance first, then τ
    for (idx, (name_en, name_zh, ..)) in ELEMENTS.iter().enumerate() {
        if *name_en == "earth" {
            continue;
        }
        let p0 = heliocentric(idx, t);
        let d0 = dist(&p0, &earth);
        let tau_centuries = (d0 * 499.005) / 86_400.0 / 36_525.0; // light time (AU → s)
        let p = heliocentric(idx, t - tau_centuries);
        let g = [p[0] - earth[0], p[1] - earth[1], p[2] - earth[2]];
        let (ra, dec) = ecl_to_radec(g[0], g[1], g[2]);
        out.push(SolarBody {
            name_en,
            name_zh,
            ra_deg: ra,
            dec_deg: dec,
            angular_radius_deg: None,
        });
    }
    out
}

fn dist(a: &[f64; 3], b: &[f64; 3]) -> f64 {
    ((a[0] - b[0]).powi(2) + (a[1] - b[1]).powi(2) + (a[2] - b[2]).powi(2)).sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn err_deg(ra1: f64, dec1: f64, ra2: f64, dec2: f64) -> f64 {
        let (r1, d1, r2, d2) = (
            ra1.to_radians(),
            dec1.to_radians(),
            ra2.to_radians(),
            dec2.to_radians(),
        );
        (d1.sin() * d2.sin() + d1.cos() * d2.cos() * (r1 - r2).cos())
            .clamp(-1.0, 1.0)
            .acos()
            .to_degrees()
    }

    /// Anchors from astropy's builtin ephemeris (2026-08-31T00:00:00Z, unix_ms 1788134400000)
    #[test]
    fn matches_astropy_anchors_2026_08_31() {
        const ANCHORS: [(&str, f64, f64); 9] = [
            ("Sun", 158.9576, 8.8473),
            ("Moon", 9.1817, 7.8037),
            ("mercury", 162.5623, 9.1629),
            ("venus", 199.0908, -11.5893),
            ("mars", 103.5097, 23.3765),
            ("jupiter", 135.7312, 17.3846),
            ("saturn", 13.3279, 2.8317),
            ("uranus", 63.3738, 21.0249),
            ("neptune", 3.6043, 0.0223),
        ];
        let bodies = solar_system_positions(1_788_134_400_000);
        for (name, ra, dec) in ANCHORS {
            let b = bodies
                .iter()
                .find(|b| b.name_en.eq_ignore_ascii_case(name))
                .unwrap_or_else(|| panic!("{name} missing"));
            let tol = match name {
                "Moon" => 0.35, // truncated series, geocentric (the astropy anchor is geocentric too)
                "mercury" => 0.25, // the innermost planet is most sensitive to truncated elements
                _ => 0.2,
            };
            let e = err_deg(b.ra_deg, b.dec_deg, ra, dec);
            assert!(
                e < tol,
                "{name}: err {e:.3}° (got {:.3},{:.3} want {ra},{dec})",
                b.ra_deg,
                b.dec_deg
            );
        }
    }

    /// Moon topocentric parallax: < 0.1° against astropy **topocentric** anchors.
    /// Anchors from `scripts/verify/check_moon_topocentric.py` (astropy `get_body('moon', t, location)`).
    /// Also checks the converse: without the correction the error exceeds 0.7°, so losing it is caught.
    #[test]
    fn moon_topocentric_matches_astropy_within_0p1_deg() {
        // (unix_ms, lat, lon, alt_m, astropy topocentric ra, dec)
        const ANCHORS: [(i64, f64, f64, f64, f64, f64); 4] = [
            (1_788_134_400_000, 31.2, 121.5, 10.0, 8.3529, 7.3103), // Shanghai
            (1_760_000_000_000, 31.2, 121.5, 10.0, 43.8641, 20.5141), // Shanghai, another phase
            (1_800_000_000_000, -33.9, 18.4, 100.0, 15.7182, 11.6630), // Cape Town (southern hemisphere)
            (1_704_110_400_000, 64.0, -21.9, 50.0, 163.8306, 9.3612),  // Reykjavik (high latitude)
        ];
        for (ms, lat, lon, alt, ra, dec) in ANCHORS {
            let obs = Observer {
                lat_deg: lat,
                lon_deg: lon,
                alt_m: alt,
            };
            obs.validate().unwrap();
            let topo = solar_system_positions_at(ms, Some(&obs));
            let m = topo.iter().find(|b| b.name_en == "Moon").unwrap();
            let e = err_deg(m.ra_deg, m.dec_deg, ra, dec);
            assert!(
                e < 0.1,
                "topocentric moon err {e:.3}° at {ms} ({lat},{lon})"
            );

            let geo = solar_system_positions(ms);
            let g = geo.iter().find(|b| b.name_en == "Moon").unwrap();
            let without = err_deg(g.ra_deg, g.dec_deg, ra, dec);
            assert!(
                without > 0.7,
                "geocentric should be far off the topocentric anchor, got {without:.3}° at {ms}"
            );
            // The apparent radius depends on topocentric distance (larger when nearer); check magnitude only
            assert!((0.24..=0.29).contains(&m.angular_radius_deg.unwrap()));
        }
    }

    /// Out-of-range observers are errors, not clamped (a wrong latitude sign is off by 2°)
    #[test]
    fn observer_out_of_range_is_rejected() {
        assert!(Observer {
            lat_deg: 91.0,
            lon_deg: 0.0,
            alt_m: 0.0
        }
        .validate()
        .is_err());
        assert!(Observer {
            lat_deg: 0.0,
            lon_deg: 400.0,
            alt_m: 0.0
        }
        .validate()
        .is_err());
        assert!(Observer {
            lat_deg: f64::NAN,
            lon_deg: 0.0,
            alt_m: 0.0
        }
        .validate()
        .is_err());
        assert!(Observer {
            lat_deg: -33.9,
            lon_deg: 18.4,
            alt_m: 100.0
        }
        .validate()
        .is_ok());
    }

    /// Meeus 47.a worked example: 1992-04-12 0 TT (astropy cross-check ra 134.79, dec 13.739)
    #[test]
    fn meeus_moon_example() {
        // 1992-04-12T00:00:00 TT ≈ UTC − 58.2 s, irrelevant at 0.3° tolerance: use UTC ms
        let unix_ms = 703_036_800_000i64;
        let t = centuries(unix_ms);
        let (ra, dec, dist_km) = moon_radec(t);
        assert!(
            err_deg(ra, dec, 134.79, 13.739) < 0.3,
            "moon {ra:.3},{dec:.3}"
        );
        assert!((dist_km - 368_409.7).abs() < 500.0, "dist {dist_km}");
    }
}
