#!/usr/bin/env python3
"""Lists the licenses of the Rust crates that end up in shipped binaries.

Runtime (normal) dependencies of unisolver-core, unisolver-cabi and the Flutter plugin's
unisolver_frb, for every target; build tools and test-only crates are excluded. The table
is written between the markers in THIRD_PARTY_LICENSES.md.

Usage: rust_licenses.py           rewrite the table
       rust_licenses.py --check   exit 1 when the table is out of date
"""
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "THIRD_PARTY_LICENSES.md"
BEGIN, END = "<!-- rust-licenses:begin -->", "<!-- rust-licenses:end -->"
OURS = {"unisolver-core", "unisolver-cabi", "unisolver_frb", "tetra3"}
# Crates that ship a license file instead of an SPDX expression (checked by hand)
LICENSE_FILE = {"allo-isolate": "Apache-2.0 (license file)"}


def crates():
    out = subprocess.run(
        # --color never: with CARGO_TERM_COLOR=always (set in CI) the "(*)" markers carry ANSI codes
        ["cargo", "tree", "--color", "never", "-e", "normal", "--target", "all",
         "-p", "unisolver-core", "-p", "unisolver-cabi", "-p", "unisolver_frb",
         "--features", "unisolver-core/imageio unisolver-core/satellites",
         "--prefix", "none", "--format", "{p}|{l}"],
        cwd=ROOT, check=True, capture_output=True, text=True).stdout
    seen = {}
    for line in out.splitlines():
        pkg, _, lic = line.partition("|")
        m = re.match(r"(\S+) v(\S+)", pkg)
        if not m or m.group(1) in OURS:
            continue
        lic = lic.replace(" (*)", "").strip() or LICENSE_FILE.get(m.group(1), "unknown")
        seen[(m.group(1), m.group(2))] = lic
    return seen


def table(seen):
    by_license = defaultdict(list)
    for (name, version), lic in seen.items():
        by_license[lic].append(f"{name} {version}")
    unknown = sorted(n for (n, _), l in seen.items() if l == "unknown")
    if unknown:
        sys.exit(f"crates without a known license: {', '.join(unknown)} (add them to LICENSE_FILE)")
    lines = [BEGIN, "",
             f"{len(seen)} crates, generated by `scripts/ci/rust_licenses.py`.", "",
             "| License | Crates |", "|---|---|"]
    for lic in sorted(by_license, key=lambda l: (-len(by_license[l]), l)):
        lines.append(f"| {lic} | {', '.join(sorted(by_license[lic]))} |")
    lines += ["", END]
    return "\n".join(lines)


def main():
    text = TARGET.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit(f"{TARGET.name}: markers {BEGIN} / {END} not found")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + table(crates()) + tail
    if "--check" in sys.argv[1:]:
        if new != text:
            print("THIRD_PARTY_LICENSES.md is out of date: run scripts/ci/rust_licenses.py")
            return 1
        print("rust licenses up to date")
        return 0
    TARGET.write_text(new, encoding="utf-8")
    print(f"wrote {TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
