#ifndef UNISOLVER_H
#define UNISOLVER_H

/* Generated by cbindgen from unisolver-cabi. Do not edit; run `cargo build -p unisolver-cabi`. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Ownership and lifetimes
 * =======================
 * Every pointer this library returns is allocated by Rust and must be released
 * with the matching unisolver_*_close / unisolver_string_free, never with free()
 * or delete. Every release function accepts NULL as a no-op.
 *
 * Owned by the caller (must be released):
 *   - UnisolverSolver*     unisolver_open             -> unisolver_close
 *   - UnisolverPool*       unisolver_pool_open        -> unisolver_pool_close
 *   - UnisolverAnnotator*  unisolver_*annotator_open  -> unisolver_annotator_close
 *   - UnisolverCalibration* unisolver_calibration_open -> unisolver_calibration_close
 *   - char* (JSON results and *error_out)             -> unisolver_string_free
 * Errors: a function with `char** error_out` sets *error_out = NULL on success;
 * on failure it writes an OWNED message and returns NULL/false.
 * Threads: one UnisolverSolver may run solves concurrently (shared read-only);
 * no call may be in flight when it is closed. Calls that change a pool or a
 * calibration session must not overlap other calls on the same handle.
 */

/**
 * Opaque annotator handle. Release with [`unisolver_annotator_close`].
 *
 * **Build once and keep it**: construction reads and parses the DSO catalog (771 KB) and the
 * names pack (215 KB) in about 2.1 ms, while annotating a frame takes about 1 ms; rebuilding
 * per solve triples the cost.
 */
typedef struct UnisolverAnnotator UnisolverAnnotator;

/**
 * Opaque calibration session handle. Release with [`unisolver_calibration_close`].
 *
 * **Not thread-safe**: `add_image_json` changes the session, so no other call may be in
 * flight on the same session (separate sessions are independent).
 */
typedef struct UnisolverCalibration UnisolverCalibration;

/**
 * Opaque pool handle. Release with [`unisolver_pool_close`].
 */
typedef struct UnisolverPool UnisolverPool;

/**
 * Opaque solver handle. Release with [`unisolver_close`].
 */
typedef struct UnisolverSolver UnisolverSolver;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version (static string; do not free).
 */
const char *unisolver_version(void);

/**
 * Attributions for the data the engine ships or reads, as an OWNED JSON array (free
 * it with unisolver_string_free). Each entry has `id`, `name`, `applies_to`, `license`,
 * `text` and `url`; show the `text` of the sources your app uses (Gaia DR3 requires it).
 */
char *unisolver_attributions_json(void);

/**
 * Opens a solver database. On failure returns NULL and sets `error_out` (free it with
 * unisolver_string_free).
 *
 * # Safety
 * `db_path` must be a valid NUL-terminated string; `error_out` is NULL or a writable pointer slot.
 */
UnisolverSolver *unisolver_open(const char *db_path, char **error_out);

/**
 * Releases a solver. Accepts NULL.
 *
 * # Safety
 * `solver` must come from unisolver_open and not be freed yet; no call may be in flight on it.
 */
void unisolver_close(UnisolverSolver *solver);

/**
 * Solves an image file (FITS/XISF/PNG/JPEG/TIFF detected automatically; a header FOV is
 * only a hint, the aspect ladder follows on failure). Returns OWNED JSON (free with
 * unisolver_string_free).
 *
 * To pass options (known FOV / calibrated camera / tracking hint / profile / timeout) use
 * [`unisolver_solve_image_json_opts`].
 *
 * # Safety
 * `path` is a valid NUL-terminated string; `solver` is live; `error_out` as above.
 */
char *unisolver_solve_image_json(const UnisolverSolver *solver, const char *path, char **error_out);

/**
 * Solve with options: `opts_json` per [`SolveOptsJson`] (NULL or `{}` is the same as
 * [`unisolver_solve_image_json`]). Known FOV, calibrated camera, tracking hint, extraction
 * profile and timeout all come in here.
 *
 * **Tracking** (burst capture, guiding, centring loops): put the previous frame's attitude
 * quaternion in `attitude_hint_wxyz` and give `fov_deg` or `camera`. The solve skips the
 * 4-star hash search and matches catalog stars projected around the hint: 3 stars suffice
 * (a blind solve needs 4). With `strict_hint` false a failure falls back to a blind solve.
 *
 * # Safety
 * `solver` is live; `path` is a valid NUL-terminated string; `opts_json` is NULL or a valid
 * NUL-terminated string; `error_out` as above.
 */
char *unisolver_solve_image_json_opts(const UnisolverSolver *solver,
                                      const char *path,
                                      const char *opts_json,
                                      char **error_out);

/**
 * **Direct frame input**: solves pixels in memory without touching disk. Use it for camera
 * callbacks, video streams and already-decoded frames instead of writing a temporary file.
 *
 * - `pixels` / `len`: the pixel buffer and its length in bytes. **It is copied**: a camera
 *   callback's buffer is usually reclaimed at once and cannot be assumed to outlive the solve.
 * - `kind`: `luma8` / `luma16` / `luma_f32` / `rgba8`; multi-byte samples are **native-endian**.
 * - `row_stride_bytes`: bytes per source row, for padded buffers (Android `YUV_420_888`
 *   Y-plane rowStride, iOS `bytesPerRow`); 0 when tightly packed.
 * - `opts_json`: as [`unisolver_solve_image_json_opts`]. A raw frame has **no header**, so
 *   without `fov_deg`/`camera` the fallback is the aspect ladder, not header hints; a photo
 *   decoded by the platform (HEIC) passes its EXIF as `focal_length_35mm` (tried first) and
 *   `observation_unix_ms`. Live and tracking use should pass `fov_deg` and
 *   `attitude_hint_wxyz` anyway.
 *
 * # Safety
 * `solver` is live; `pixels` points to at least `len` readable bytes; `kind` is a valid
 * NUL-terminated string; `opts_json` is NULL or a valid NUL-terminated string.
 */
char *unisolver_solve_frame_json_opts(const UnisolverSolver *solver,
                                      const uint8_t *pixels,
                                      uintptr_t len,
                                      uint32_t width,
                                      uint32_t height,
                                      const char *kind,
                                      uint32_t row_stride_bytes,
                                      const char *opts_json,
                                      char **error_out);

/**
 * Opens a pool, registering every `*.db` in `dir`. A file that fails to open is only
 * recorded in `skipped` (see [`unisolver_pool_tiers_json`]); it fails only when **none** opens.
 *
 * # Safety
 * `dir` must be a valid NUL-terminated string; `error_out` is NULL or a writable pointer slot.
 */
UnisolverPool *unisolver_pool_open(const char *dir, char **error_out);

/**
 * Registers one more tier (call it after a download finishes). Returns the tier as OWNED
 * JSON. Registering the same file again is idempotent.
 *
 * # Safety
 * `pool` is live and **no other call may be in flight** (this call changes the pool);
 * `db_path` is a valid NUL-terminated string.
 */
char *unisolver_pool_register(UnisolverPool *pool, const char *db_path, char **error_out);

/**
 * Registered tiers plus the files skipped at open, as OWNED JSON.
 *
 * # Safety
 * `pool` is live; `error_out` as above.
 */
char *unisolver_pool_tiers_json(const UnisolverPool *pool, char **error_out);

/**
 * Solves an image file without naming a tier: header FOV hints first, the aspect ladder as
 * fallback, rungs dispatched by tier range, then a range sweep for tiers never reached.
 * Returns OWNED JSON with an extra `db` field (the tier that solved it).
 *
 * # Safety
 * `path` is a valid NUL-terminated string; `pool` is live; `error_out` as above.
 */
char *unisolver_pool_solve_image_json(const UnisolverPool *pool,
                                      const char *path,
                                      char **error_out);

/**
 * Pool solve with options: `opts_json` as [`unisolver_solve_image_json_opts`]. With
 * `fov_deg` or `camera`, only tiers covering that FOV are tried; no ladder.
 *
 * # Safety
 * `pool` is live; `path` is a valid NUL-terminated string; `opts_json` is NULL or a valid NUL-terminated string.
 */
char *unisolver_pool_solve_image_json_opts(const UnisolverPool *pool,
                                           const char *path,
                                           const char *opts_json,
                                           char **error_out);

/**
 * Direct frame input with pool routing. Parameters as [`unisolver_solve_frame_json_opts`];
 * the JSON adds `db` (the tier that solved it).
 *
 * # Safety
 * As [`unisolver_solve_frame_json_opts`], with `pool` live.
 */
char *unisolver_pool_solve_frame_json_opts(const UnisolverPool *pool,
                                           const uint8_t *pixels,
                                           uintptr_t len,
                                           uint32_t width,
                                           uint32_t height,
                                           const char *kind,
                                           uint32_t row_stride_bytes,
                                           const char *opts_json,
                                           char **error_out);

/**
 * Releases a pool. Accepts NULL.
 *
 * # Safety
 * `pool` must come from unisolver_pool_open and not be freed yet; no call may be in flight on it.
 */
void unisolver_pool_close(UnisolverPool *pool);

/**
 * Topocentric satellite positions (TLE + SGP4). `tle_text` holds two- or three-line sets,
 * **fetched by the caller** (this library never goes online). Returns an OWNED JSON array;
 * empty text gives `[]`, while text with no parsable set is an error (an empty array would
 * read as "no passes").
 *
 * # Safety
 * `tle_text` must be a valid NUL-terminated string; `error_out` is NULL or a writable pointer slot.
 */
char *unisolver_satellites_json(const char *tle_text,
                                int64_t unix_ms,
                                double lat_deg,
                                double lon_deg,
                                double alt_m,
                                char **error_out);

/**
 * Builds an annotator from a single-database handle. `dso_path` / `names_path` may be NULL
 * (see the struct docs).
 *
 * # Safety
 * `solver` is live; both paths are NULL or valid NUL-terminated strings; `error_out` as above.
 */
UnisolverAnnotator *unisolver_annotator_open(const UnisolverSolver *solver,
                                             const char *dso_path,
                                             const char *names_path,
                                             char **error_out);

/**
 * Builds an annotator from **one tier** of a pool. Pass the tier that solved the frame (the
 * `db` field of the solve JSON); NULL uses the widest tier. Narrow tiers have denser
 * catalogs, so annotate with the one that solved.
 *
 * # Safety
 * `pool` is live; `db_name` is NULL or a valid NUL-terminated string; the rest as above.
 */
UnisolverAnnotator *unisolver_pool_annotator_open(const UnisolverPool *pool,
                                                  const char *db_name,
                                                  const char *dso_path,
                                                  const char *names_path,
                                                  char **error_out);

/**
 * Languages in the names pack, as an OWNED JSON array. Empty means no names pack (English only).
 *
 * # Safety
 * `annotator` is live; `error_out` as above.
 */
char *unisolver_annotator_languages_json(const UnisolverAnnotator *annotator, char **error_out);

/**
 * Loads the constellation pack (`unisolver_constellations.bin`) into an annotator, for the
 * `include_constellations` and `constellation_boundaries` options. Returns true when loaded;
 * on failure returns false with `error_out` set, and the annotator stays usable (those layers
 * report themselves unavailable, with the reason, as a missing DSO catalog does).
 *
 * # Safety
 * `annotator` is live and no other call is in flight on it; `path` is a valid NUL-terminated
 * string; `error_out` is NULL or a writable pointer slot.
 */
bool unisolver_annotator_load_constellations(UnisolverAnnotator *annotator,
                                             const char *path,
                                             char **error_out);

/**
 * Annotates a frame from the `wcs` object of the solve JSON, unchanged; returns OWNED annotation JSON.
 *
 * `opts_json` may be NULL or `{}` (all defaults); fields are listed on `AnnotateOptsJson`.
 * The usual ones are `language` (`zh_cn` / `ja` / …), `observation_unix_ms` (required by the
 * solar-system and satellite layers), `observer` (moon parallax; required by satellites) and
 * `satellite_tle`.
 *
 * The result is **data**: pixel coordinates (top-left origin), names, apparent sizes and
 * orientations for each layer, plus `layers` (availability and the reason for anything
 * unavailable or degraded). **Drawing is the caller's job**; this library does not render.
 *
 * # Safety
 * `annotator` is live; `wcs_json` is a valid NUL-terminated string; `opts_json` is NULL or
 * a valid NUL-terminated string; `error_out` as above.
 */
char *unisolver_annotate_json(const UnisolverAnnotator *annotator,
                              const char *wcs_json,
                              const char *opts_json,
                              char **error_out);

/**
 * Releases an annotator. Accepts NULL.
 *
 * # Safety
 * `annotator` must come from this library and not be freed yet; no call may be in flight on it.
 */
void unisolver_annotator_close(UnisolverAnnotator *annotator);

/**
 * Opens a calibration session: feed it several images of the **same size**, then fit the
 * camera (including distortion). On real data the radial model reduced the RMSE from
 * 11.3 px to 1.4 px.
 *
 * # Safety
 * `solver` is live; `error_out` as above.
 */
UnisolverCalibration *unisolver_calibration_open(const UnisolverSolver *solver, char **error_out);

/**
 * Adds an image to the session and returns its solve JSON (same shape as the solve entries).
 * **Only solved frames join the session**; for the others the status tells the caller to
 * ask for another shot. `opts_json` as [`unisolver_solve_image_json_opts`] (NULL = defaults).
 *
 * # Safety
 * `cal` is live and **no other call is in flight**; `path` is a valid NUL-terminated string;
 * `opts_json` is NULL or a valid NUL-terminated string.
 */
char *unisolver_calibration_add_image_json(UnisolverCalibration *cal,
                                           const char *path,
                                           const char *opts_json,
                                           char **error_out);

/**
 * Frames accepted into the session (solved); -1 when `cal` is NULL.
 *
 * # Safety
 * `cal` is NULL or live.
 */
int32_t unisolver_calibration_count(const UnisolverCalibration *cal);

/**
 * Fits the camera. `model_json` is NULL or `{"model":"radial"}` / `{"model":"polynomial","order":3}`.
 * Returns an OWNED report: `camera` (persist it and pass it back as `camera` to skip the
 * ladder), `rmse_before_px` / `rmse_after_px` / `n_inliers` / `n_outliers` / `frames_used`.
 *
 * # Safety
 * `cal` is live; `model_json` is NULL or a valid NUL-terminated string.
 */
char *unisolver_calibration_fit_json(const UnisolverCalibration *cal,
                                     const char *model_json,
                                     char **error_out);

/**
 * Releases a calibration session. Accepts NULL.
 *
 * # Safety
 * `cal` must come from this library and not be freed yet; no call may be in flight on it.
 */
void unisolver_calibration_close(UnisolverCalibration *cal);

/**
 * Releases a string returned by this library. Accepts NULL.
 *
 * # Safety
 * `value` must be a string returned by this library and not freed yet.
 */
void unisolver_string_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UNISOLVER_H */
