// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Every data source in the engine's databases, catalogs and names pack.
List<DataAttributionDto> dataAttributions() =>
    RustLib.instance.api.crateApiAttributionDataAttributions();

/// One data source and the attribution its license asks for.
class DataAttributionDto {
  /// Stable identifier (`gaia`, `hipparcos`, `iau_wgsn`, `openngc`, `stellarium`)
  final String id;
  final String name;

  /// What in the engine derives from it
  final String appliesTo;

  /// SPDX-style license identifier
  final String license;

  /// Text to show in the app
  final String text;
  final String url;

  const DataAttributionDto({
    required this.id,
    required this.name,
    required this.appliesTo,
    required this.license,
    required this.text,
    required this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      appliesTo.hashCode ^
      license.hashCode ^
      text.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataAttributionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          appliesTo == other.appliesTo &&
          license == other.license &&
          text == other.text &&
          url == other.url;
}
