// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Decompresses a zstd database to `out_path`; skips when the target exists and is non-empty.
/// Returns the decompressed size in bytes.
Future<BigInt> installCompressedDb({
  required String zstPath,
  required String outPath,
}) => RustLib.instance.api.crateApiInstallInstallCompressedDb(
  zstPath: zstPath,
  outPath: outPath,
);

/// Streaming sha256 of a file (lowercase hex), for download verification: a tier of several
/// hundred MB should not be read into memory on the Dart side to hash it.
Future<String> sha256File({required String path}) =>
    RustLib.instance.api.crateApiInstallSha256File(path: path);
