// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `forward`

/// Registers the Dart log stream; the first call installs the global subscriber, later calls
/// replace the sink.
Stream<LogEventDto> setLogStream() =>
    RustLib.instance.api.crateApiLoggingSetLogStream();

class LogEventDto {
  final String level;
  final String target;
  final String message;

  const LogEventDto({
    required this.level,
    required this.target,
    required this.message,
  });

  @override
  int get hashCode => level.hashCode ^ target.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEventDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          target == other.target &&
          message == other.message;
}
