// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Preview of an image file (FITS / XISF / PNG / JPEG / TIFF) no larger than `max_side` on
/// either side. Astronomical frames hold linear data that shows black as-is; the stretch
/// (median and MAD based, as PixInsight's AutoSTF) lifts the sky to a quarter of full scale.
/// About 40 ms for a 26 Mpx frame.
Future<ImagePreviewDto> imagePreview({
  required String path,
  required int maxSide,
}) => RustLib.instance.api.crateApiPreviewImagePreview(
  path: path,
  maxSide: maxSide,
);

/// An auto-stretched greyscale preview as RGBA pixels (feed `rgba` to
/// `ui.decodeImageFromPixels` with `PixelFormat.rgba8888`). Drawn over the source's size
/// (`sourceWidth` × `sourceHeight`), it lines up with the source's pixel coordinates, so
/// annotations land where they belong.
class ImagePreviewDto {
  final int width;
  final int height;
  final int sourceWidth;
  final int sourceHeight;

  /// `width × height × 4` bytes
  final Uint8List rgba;

  const ImagePreviewDto({
    required this.width,
    required this.height,
    required this.sourceWidth,
    required this.sourceHeight,
    required this.rgba,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      sourceWidth.hashCode ^
      sourceHeight.hashCode ^
      rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImagePreviewDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          sourceWidth == other.sourceWidth &&
          sourceHeight == other.sourceHeight &&
          rgba == other.rgba;
}
