// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

Future<List<SatellitePosDto>> satellitePositions({
  required String tleText,
  required PlatformInt64 unixMs,
  required ObserverDto observer,
}) => RustLib.instance.api.crateApiSatellitesSatellitePositions(
  tleText: tleText,
  unixMs: unixMs,
  observer: observer,
);
