// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `load_image_luma`, `load_with_header_time`

Future<String> cameraParamsToJson({required CameraParamsDto c}) =>
    RustLib.instance.api.crateApiSolverCameraParamsToJson(c: c);

Future<CameraParamsDto> cameraParamsFromJson({required String j}) =>
    RustLib.instance.api.crateApiSolverCameraParamsFromJson(j: j);

/// For Dart integration tests only: checks that a panic becomes an exception (FRB catches
/// the unwind and raises it in Dart)
Future<void> debugTriggerPanic() =>
    RustLib.instance.api.crateApiSolverDebugTriggerPanic();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UniAnnotator>>
abstract class UniAnnotator implements RustOpaqueInterface {
  Future<AnnotationsDto> annotate({
    required WcsDto wcs,
    required AnnotateOptionsDto opts,
  });

  /// The constellation containing J2000 `(raDeg, decDeg)`, named in `language` (codes as
  /// `AnnotateOptionsDto.language`). For the frame centre pass the solve's `raDeg` /
  /// `decDeg`; for a point on the image, convert it with `wcsPixelsToSky` first. Null
  /// without a constellation pack (`annotate` reports why in `layers.reasons`).
  ConstellationNameDto? constellationAt({
    required double raDeg,
    required double decDeg,
    required String language,
  });

  /// Languages in the names pack (empty = no names pack, English only).
  List<String> languages();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UniCalibration>>
abstract class UniCalibration implements RustOpaqueInterface {
  Future<SolveOutcomeDto> addImageFile({
    required String path,
    required SolveOptionsDto opts,
  });

  int count();

  Future<CalibrationReportDto> fit({required CalibModelDto model});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UniSolver>>
abstract class UniSolver implements RustOpaqueInterface {
  /// Annotator. Each file is optional: a missing one leaves its layer unavailable, with the
  /// reason in `layers.reasons`. `constellationsPath` is the constellation pack
  /// (`UnisolverAssets.installConstellations()`).
  Future<UniAnnotator> annotator({
    String? dsoPath,
    String? namesPath,
    String? constellationsPath,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<UniSolver> newInstance({required String dbPath}) =>
      RustLib.instance.api.crateApiSolverUniSolverNew(dbPath: dbPath);

  Future<UniCalibration> newCalibration();

  DbPropertiesDto properties();

  Future<SolveOutcomeDto> solveFrame({
    required FrameDto frame,
    required SolveOptionsDto opts,
  });

  Future<SolveOutcomeDto> solveImageFile({
    required String path,
    required SolveOptionsDto opts,
  });

  /// Fully automatic file entry (same strategy as the C ABI's solve_image_json): header FOV
  /// hints (FITS focal length and pixel size, EXIF 35 mm focal length) first, the aspect
  /// ladder as fallback, rungs clamped to the database range; the header's observation time
  /// fills in when `base` has none. For FITS/XISF prefer ExtractionProfileDto.auto() or
  /// cleanSensor().
  Future<LadderOutcomeDto> solveImageFileAuto({
    required String path,
    required SolveOptionsDto base,
  });

  Future<LadderOutcomeDto> solveImageFileWithPresets({
    required String path,
    required SolveOptionsDto base,
    required List<FovPresetDto> presets,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UniSolverPool>>
abstract class UniSolverPool implements RustOpaqueInterface {
  /// Annotator. Pass the tier that solved the frame (`PoolOutcomeDto.db`), since narrow tiers
  /// are denser; without it the widest tier is used. A narrow-field solve annotates with the
  /// narrowest tetra3 tier. The files are as in [`UniSolver::annotator`].
  Future<UniAnnotator> annotator({
    String? db,
    String? dsoPath,
    String? namesPath,
    String? constellationsPath,
  });

  /// Empty pool: for a first launch with nothing installed; then [`Self::register`] tier by tier.
  static Future<UniSolverPool> empty() =>
      RustLib.instance.api.crateApiSolverUniSolverPoolEmpty();

  /// Registers every `*.db` in the directory. A broken file is skipped (see [`Self::skipped`]);
  /// it fails only when none opens, since an empty handle is harder to debug than an error.
  static Future<UniSolverPool> openDir({required String dir}) =>
      RustLib.instance.api.crateApiSolverUniSolverPoolOpenDir(dir: dir);

  /// Registers one more tier (after an install). Registering the same file again is idempotent.
  Future<TierInfoDto> register({required String dbPath});

  /// Registers the narrow-field package (desktop builds): its blind index and star-tile
  /// files. Only their headers are read. Registering the same index again returns it; a
  /// second package is an error, and so is every call on iOS and Android, which have no
  /// narrow-field engine.
  Future<TierInfoDto> registerNarrow({
    required String indexPath,
    required String starsPath,
  });

  /// Files skipped when the directory was opened, as `"<path>: <reason>"`.
  List<String> skipped();

  /// Camera frames and decoded photos (no file header): the aspect ladder, preceded by the
  /// FOV of `opts.focalLength35mm` when the app read one from EXIF; routed across tiers.
  Future<PoolOutcomeDto> solveFrameAuto({
    required FrameDto frame,
    required SolveOptionsDto opts,
  });

  /// Fully automatic file entry without naming a tier (the one apps should use): load any
  /// of the five formats → header FOV hints (FITS, EXIF) + aspect ladder → cross-tier
  /// routing. The header's observation time fills in when `base` has none and comes back in
  /// `outcome.observationUnixMs`. HEIC is not decoded: decode it with the platform and use
  /// [`Self::solve_frame_auto`].
  Future<PoolOutcomeDto> solveImageFileAuto({
    required String path,
    required SolveOptionsDto base,
  });

  /// Registered tiers: the tetra3 tiers wide to narrow, then the narrow-field engine.
  Future<List<TierInfoDto>> tiers();
}
