// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`, `try_from`, `try_from`

class AnnotateOptionsDto {
  final double? starMaxMag;
  final int maxStars;
  final bool includeStarNames;
  final bool includeDso;

  /// Drops fainter deep-sky objects, or those without a magnitude, except outlined ones
  final double? dsoMaxMag;

  /// Projected outlines of extended objects (`DsoAnnotationDto.outlines`)
  final bool dsoOutlines;

  /// Highest outline level: 1 = faint outer edge … 3 = bright core
  final int maxOutlineLevel;
  final bool includeSolarSystem;
  final PlatformInt64? observationUnixMs;

  /// Observer: when given, the **moon** gets its topocentric parallax (without it the moon can
  /// be off by 1°, two lunar diameters); required by the satellite layer. Planets and the sun
  /// are unaffected (parallax ≤ 0.003°).
  final ObserverDto? observer;

  /// TLE text for the satellite layer (fetched by the caller; the engine never goes online);
  /// also needs observation_unix_ms and observer.
  final String? satelliteTle;

  /// Language code: `en` / `zh_cn` / `zh_tw` / `ja` / `ko` / `fr` / `de` / `es` / `it` /
  /// `ru` / `pl` / `hu` / `ro` (as in the names pack; `UniAnnotator.languages()` lists them).
  /// Lenient: `zh-CN`, `zh_Hans` and `zh` map to Simplified Chinese; English when missing.
  final String language;

  const AnnotateOptionsDto({
    this.starMaxMag,
    required this.maxStars,
    required this.includeStarNames,
    required this.includeDso,
    this.dsoMaxMag,
    required this.dsoOutlines,
    required this.maxOutlineLevel,
    required this.includeSolarSystem,
    this.observationUnixMs,
    this.observer,
    this.satelliteTle,
    required this.language,
  });

  static AnnotateOptionsDto defaults() =>
      RustLib.instance.api.crateApiTypesAnnotateOptionsDtoDefaults();

  @override
  int get hashCode =>
      starMaxMag.hashCode ^
      maxStars.hashCode ^
      includeStarNames.hashCode ^
      includeDso.hashCode ^
      dsoMaxMag.hashCode ^
      dsoOutlines.hashCode ^
      maxOutlineLevel.hashCode ^
      includeSolarSystem.hashCode ^
      observationUnixMs.hashCode ^
      observer.hashCode ^
      satelliteTle.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnnotateOptionsDto &&
          runtimeType == other.runtimeType &&
          starMaxMag == other.starMaxMag &&
          maxStars == other.maxStars &&
          includeStarNames == other.includeStarNames &&
          includeDso == other.includeDso &&
          dsoMaxMag == other.dsoMaxMag &&
          dsoOutlines == other.dsoOutlines &&
          maxOutlineLevel == other.maxOutlineLevel &&
          includeSolarSystem == other.includeSolarSystem &&
          observationUnixMs == other.observationUnixMs &&
          observer == other.observer &&
          satelliteTle == other.satelliteTle &&
          language == other.language;
}

class AnnotationsDto {
  final List<StarAnnotationDto> stars;
  final List<NamedStarAnnotationDto> namedStars;
  final List<DsoAnnotationDto> objects;
  final List<SolarAnnotationDto> solar;
  final List<SatelliteAnnotationDto> satellites;
  final LayerAvailabilityDto layers;

  const AnnotationsDto({
    required this.stars,
    required this.namedStars,
    required this.objects,
    required this.solar,
    required this.satellites,
    required this.layers,
  });

  @override
  int get hashCode =>
      stars.hashCode ^
      namedStars.hashCode ^
      objects.hashCode ^
      solar.hashCode ^
      satellites.hashCode ^
      layers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnnotationsDto &&
          runtimeType == other.runtimeType &&
          stars == other.stars &&
          namedStars == other.namedStars &&
          objects == other.objects &&
          solar == other.solar &&
          satellites == other.satellites &&
          layers == other.layers;
}

@freezed
sealed class CalibModelDto with _$CalibModelDto {
  const CalibModelDto._();

  const factory CalibModelDto.radial() = CalibModelDto_Radial;
  const factory CalibModelDto.polynomial({required int order}) =
      CalibModelDto_Polynomial;
}

class CalibrationReportDto {
  final CameraParamsDto camera;
  final double rmseBeforePx;
  final double rmseAfterPx;
  final int nInliers;
  final int nOutliers;
  final int framesUsed;

  const CalibrationReportDto({
    required this.camera,
    required this.rmseBeforePx,
    required this.rmseAfterPx,
    required this.nInliers,
    required this.nOutliers,
    required this.framesUsed,
  });

  @override
  int get hashCode =>
      camera.hashCode ^
      rmseBeforePx.hashCode ^
      rmseAfterPx.hashCode ^
      nInliers.hashCode ^
      nOutliers.hashCode ^
      framesUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibrationReportDto &&
          runtimeType == other.runtimeType &&
          camera == other.camera &&
          rmseBeforePx == other.rmseBeforePx &&
          rmseAfterPx == other.rmseAfterPx &&
          nInliers == other.nInliers &&
          nOutliers == other.nOutliers &&
          framesUsed == other.framesUsed;
}

class CameraParamsDto {
  final double focalLengthPx;
  final double ppX;
  final double ppY;
  final bool parityFlip;
  final DistortionDto distortion;

  const CameraParamsDto({
    required this.focalLengthPx,
    required this.ppX,
    required this.ppY,
    required this.parityFlip,
    required this.distortion,
  });

  @override
  int get hashCode =>
      focalLengthPx.hashCode ^
      ppX.hashCode ^
      ppY.hashCode ^
      parityFlip.hashCode ^
      distortion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraParamsDto &&
          runtimeType == other.runtimeType &&
          focalLengthPx == other.focalLengthPx &&
          ppX == other.ppX &&
          ppY == other.ppY &&
          parityFlip == other.parityFlip &&
          distortion == other.distortion;
}

class CentroidDto {
  final double x;
  final double y;
  final double? mass;

  /// Axis ratio (1.0 = round star); trailing or tracking error raises it
  final double? elongation;

  const CentroidDto({
    required this.x,
    required this.y,
    this.mass,
    this.elongation,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ mass.hashCode ^ elongation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CentroidDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          mass == other.mass &&
          elongation == other.elongation;
}

class DbPropertiesDto {
  final double minFovDeg;
  final double maxFovDeg;
  final BigInt numStars;
  final int numPatterns;
  final double starMaxMagnitude;

  const DbPropertiesDto({
    required this.minFovDeg,
    required this.maxFovDeg,
    required this.numStars,
    required this.numPatterns,
    required this.starMaxMagnitude,
  });

  @override
  int get hashCode =>
      minFovDeg.hashCode ^
      maxFovDeg.hashCode ^
      numStars.hashCode ^
      numPatterns.hashCode ^
      starMaxMagnitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbPropertiesDto &&
          runtimeType == other.runtimeType &&
          minFovDeg == other.minFovDeg &&
          maxFovDeg == other.maxFovDeg &&
          numStars == other.numStars &&
          numPatterns == other.numPatterns &&
          starMaxMagnitude == other.starMaxMagnitude;
}

@freezed
sealed class DistortionDto with _$DistortionDto {
  const DistortionDto._();

  const factory DistortionDto.none() = DistortionDto_None;
  const factory DistortionDto.radial({
    required double k1,
    required double k2,
    required double k3,
    required double p1,
    required double p2,
    double? centerX,
    double? centerY,
  }) = DistortionDto_Radial;
  const factory DistortionDto.polynomial({
    required int order,
    required double scale,
    required Float64List aCoeffs,
    required Float64List bCoeffs,
  }) = DistortionDto_Polynomial;
}

class DsoAnnotationDto {
  final double x;
  final double y;
  final double semiMajorPx;
  final double semiMinorPx;

  /// None = orientation unknown: draw a circle of the semi-major axis, never guess an angle
  final double? angleDeg;
  final String designation;
  final String? commonName;
  final DsoKindDto kind;
  final double? mag;

  /// Outlines in pixels, outermost level first (empty for most objects). For an outlined
  /// object `x`/`y` may lie outside the image while part of the outline is inside.
  final List<DsoOutlineDto> outlines;

  const DsoAnnotationDto({
    required this.x,
    required this.y,
    required this.semiMajorPx,
    required this.semiMinorPx,
    this.angleDeg,
    required this.designation,
    this.commonName,
    required this.kind,
    this.mag,
    required this.outlines,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      semiMajorPx.hashCode ^
      semiMinorPx.hashCode ^
      angleDeg.hashCode ^
      designation.hashCode ^
      commonName.hashCode ^
      kind.hashCode ^
      mag.hashCode ^
      outlines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DsoAnnotationDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          semiMajorPx == other.semiMajorPx &&
          semiMinorPx == other.semiMinorPx &&
          angleDeg == other.angleDeg &&
          designation == other.designation &&
          commonName == other.commonName &&
          kind == other.kind &&
          mag == other.mag &&
          outlines == other.outlines;
}

enum DsoKindDto {
  galaxy,
  openCluster,
  globularCluster,
  nebula,
  planetaryNebula,
  hiiRegion,
  supernovaRemnant,
  darkNebula,
  clusterWithNebula,
  association,
  other,
}

/// One brightness level of a projected outline.
class DsoOutlineDto {
  /// 1 = faint outer edge … 3 = bright core
  final int level;
  final List<OutlineContourDto> contours;

  const DsoOutlineDto({required this.level, required this.contours});

  @override
  int get hashCode => level.hashCode ^ contours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DsoOutlineDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          contours == other.contours;
}

@freezed
sealed class ExtractionProfileDto with _$ExtractionProfileDto {
  const ExtractionProfileDto._();

  const factory ExtractionProfileDto.auto() = ExtractionProfileDto_Auto;
  const factory ExtractionProfileDto.phoneJpeg() =
      ExtractionProfileDto_PhoneJpeg;
  const factory ExtractionProfileDto.cleanSensor() =
      ExtractionProfileDto_CleanSensor;
  const factory ExtractionProfileDto.customCcl({
    required double sigma,
    required int maxCentroids,
  }) = ExtractionProfileDto_CustomCcl;
  const factory ExtractionProfileDto.customFast({
    required double sigma,
    required int maxCentroids,
  }) = ExtractionProfileDto_CustomFast;
}

class FovAttemptDto {
  final double fovDeg;
  final SolveStatusDto status;
  final double solveMs;

  const FovAttemptDto({
    required this.fovDeg,
    required this.status,
    required this.solveMs,
  });

  @override
  int get hashCode => fovDeg.hashCode ^ status.hashCode ^ solveMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FovAttemptDto &&
          runtimeType == other.runtimeType &&
          fovDeg == other.fovDeg &&
          status == other.status &&
          solveMs == other.solveMs;
}

class FovPresetDto {
  final double fovDeg;
  final double maxErrorDeg;

  const FovPresetDto({required this.fovDeg, required this.maxErrorDeg});

  @override
  int get hashCode => fovDeg.hashCode ^ maxErrorDeg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FovPresetDto &&
          runtimeType == other.runtimeType &&
          fovDeg == other.fovDeg &&
          maxErrorDeg == other.maxErrorDeg;
}

class FrameDto {
  final int width;
  final int height;
  final int? rowStrideBytes;
  final PixelKindDto kind;

  /// Luma16/LumaF32 are packed little-endian (a Dart Uint8List.view is little-endian)
  final Uint8List bytes;

  const FrameDto({
    required this.width,
    required this.height,
    this.rowStrideBytes,
    required this.kind,
    required this.bytes,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      rowStrideBytes.hashCode ^
      kind.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rowStrideBytes == other.rowStrideBytes &&
          kind == other.kind &&
          bytes == other.bytes;
}

class LadderOutcomeDto {
  final SolveOutcomeDto outcome;
  final List<FovAttemptDto> attempts;

  const LadderOutcomeDto({required this.outcome, required this.attempts});

  @override
  int get hashCode => outcome.hashCode ^ attempts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LadderOutcomeDto &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          attempts == other.attempts;
}

class LayerAvailabilityDto {
  final bool catalogStars;
  final bool namedStars;
  final bool dso;
  final bool solarSystem;
  final bool satellites;

  /// Why a layer is unavailable or degraded, as `(layer, message)`: show it rather than an
  /// empty layer
  final List<(String, String)> reasons;

  const LayerAvailabilityDto({
    required this.catalogStars,
    required this.namedStars,
    required this.dso,
    required this.solarSystem,
    required this.satellites,
    required this.reasons,
  });

  @override
  int get hashCode =>
      catalogStars.hashCode ^
      namedStars.hashCode ^
      dso.hashCode ^
      solarSystem.hashCode ^
      satellites.hashCode ^
      reasons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayerAvailabilityDto &&
          runtimeType == other.runtimeType &&
          catalogStars == other.catalogStars &&
          namedStars == other.namedStars &&
          dso == other.dso &&
          solarSystem == other.solarSystem &&
          satellites == other.satellites &&
          reasons == other.reasons;
}

class MatchDto {
  final int centroidIndex;
  final PlatformInt64 catalogId;
  final double x;
  final double y;

  const MatchDto({
    required this.centroidIndex,
    required this.catalogId,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode =>
      centroidIndex.hashCode ^ catalogId.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchDto &&
          runtimeType == other.runtimeType &&
          centroidIndex == other.centroidIndex &&
          catalogId == other.catalogId &&
          x == other.x &&
          y == other.y;
}

class NamedStarAnnotationDto {
  final double x;
  final double y;
  final double mag;
  final int hip;
  final String name;

  const NamedStarAnnotationDto({
    required this.x,
    required this.y,
    required this.mag,
    required this.hip,
    required this.name,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ mag.hashCode ^ hip.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NamedStarAnnotationDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          mag == other.mag &&
          hip == other.hip &&
          name == other.name;
}

/// Observer location: needed by the moon's parallax correction and the satellite layer.
class ObserverDto {
  final double latDeg;
  final double lonDeg;
  final double altM;

  const ObserverDto({
    required this.latDeg,
    required this.lonDeg,
    required this.altM,
  });

  @override
  int get hashCode => latDeg.hashCode ^ lonDeg.hashCode ^ altM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObserverDto &&
          runtimeType == other.runtimeType &&
          latDeg == other.latDeg &&
          lonDeg == other.lonDeg &&
          altM == other.altM;
}

/// A projected contour in pixels (top-left origin); a closed contour's last point joins its first.
class OutlineContourDto {
  final bool closed;

  /// Interleaved x, y
  final Float64List points;

  const OutlineContourDto({required this.closed, required this.points});

  @override
  int get hashCode => closed.hashCode ^ points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutlineContourDto &&
          runtimeType == other.runtimeType &&
          closed == other.closed &&
          points == other.points;
}

enum PixelKindDto { luma8, luma16, lumaF32, rgba8 }

/// One cross-tier attempt (a `FovAttemptDto` plus the tier it used).
class PoolAttemptDto {
  final String db;
  final double fovDeg;
  final SolveStatusDto status;
  final double solveMs;

  const PoolAttemptDto({
    required this.db,
    required this.fovDeg,
    required this.status,
    required this.solveMs,
  });

  @override
  int get hashCode =>
      db.hashCode ^ fovDeg.hashCode ^ status.hashCode ^ solveMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolAttemptDto &&
          runtimeType == other.runtimeType &&
          db == other.db &&
          fovDeg == other.fovDeg &&
          status == other.status &&
          solveMs == other.solveMs;
}

class PoolOutcomeDto {
  final SolveOutcomeDto outcome;
  final List<PoolAttemptDto> attempts;

  /// Tier that solved it (null on failure). Annotate with this tier: narrow tiers are denser
  final String? db;

  /// Extractions actually performed (evidence of reuse across tiers)
  final int extractCount;

  const PoolOutcomeDto({
    required this.outcome,
    required this.attempts,
    this.db,
    required this.extractCount,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^
      attempts.hashCode ^
      db.hashCode ^
      extractCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolOutcomeDto &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          attempts == other.attempts &&
          db == other.db &&
          extractCount == other.extractCount;
}

/// Satellite passes (above the horizon only; below it they are hidden by the Earth)
class SatelliteAnnotationDto {
  final double x;
  final double y;
  final String name;
  final double rangeKm;

  const SatelliteAnnotationDto({
    required this.x,
    required this.y,
    required this.name,
    required this.rangeKm,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ name.hashCode ^ rangeKm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SatelliteAnnotationDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          name == other.name &&
          rangeKm == other.rangeKm;
}

/// Topocentric apparent position of one satellite at a given time.
class SatellitePosDto {
  final String name;
  final double raDeg;
  final double decDeg;
  final double rangeKm;

  /// Below the horizon means hidden by the Earth: do not draw
  final bool aboveHorizon;

  const SatellitePosDto({
    required this.name,
    required this.raDeg,
    required this.decDeg,
    required this.rangeKm,
    required this.aboveHorizon,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      raDeg.hashCode ^
      decDeg.hashCode ^
      rangeKm.hashCode ^
      aboveHorizon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SatellitePosDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          raDeg == other.raDeg &&
          decDeg == other.decDeg &&
          rangeKm == other.rangeKm &&
          aboveHorizon == other.aboveHorizon;
}

class SolarAnnotationDto {
  final double x;
  final double y;
  final String name;
  final double? angularRadiusPx;

  const SolarAnnotationDto({
    required this.x,
    required this.y,
    required this.name,
    this.angularRadiusPx,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ name.hashCode ^ angularRadiusPx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolarAnnotationDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          name == other.name &&
          angularRadiusPx == other.angularRadiusPx;
}

class SolveOptionsDto {
  final double fovEstimateDeg;
  final double? fovMaxErrorDeg;
  final CameraParamsDto? camera;
  final F32Array4? attitudeHintWxyz;
  final double hintUncertaintyDeg;
  final bool strictHint;
  final ExtractionProfileDto profile;
  final bool retryAlternateProfile;

  /// Ladders only: after the staged search fails, search every rung exhaustively.
  /// Off by default so frames without stars fail in about two seconds.
  final bool thorough;
  final double matchThreshold;
  final BigInt? timeoutMs;
  final PlatformInt64? observationUnixMs;

  /// Ladders only: EXIF FocalLengthIn35mmFilm read by the app, for formats the engine does
  /// not decode (HEIC: decode with the platform and use `solveFrameAuto`). Its FOV is tried
  /// first as a hint (±15%) and the ladder still follows; ignored with a camera or a
  /// tracking hint. Files read their own EXIF.
  final double? focalLength35Mm;

  const SolveOptionsDto({
    required this.fovEstimateDeg,
    this.fovMaxErrorDeg,
    this.camera,
    this.attitudeHintWxyz,
    required this.hintUncertaintyDeg,
    required this.strictHint,
    required this.profile,
    required this.retryAlternateProfile,
    required this.thorough,
    required this.matchThreshold,
    this.timeoutMs,
    this.observationUnixMs,
    this.focalLength35Mm,
  });

  /// Defaults shared with core::SolveOptions::new (PhoneJpeg, built-in σ, 5 s timeout)
  static SolveOptionsDto defaults({required double fovEstimateDeg}) => RustLib
      .instance
      .api
      .crateApiTypesSolveOptionsDtoDefaults(fovEstimateDeg: fovEstimateDeg);

  @override
  int get hashCode =>
      fovEstimateDeg.hashCode ^
      fovMaxErrorDeg.hashCode ^
      camera.hashCode ^
      attitudeHintWxyz.hashCode ^
      hintUncertaintyDeg.hashCode ^
      strictHint.hashCode ^
      profile.hashCode ^
      retryAlternateProfile.hashCode ^
      thorough.hashCode ^
      matchThreshold.hashCode ^
      timeoutMs.hashCode ^
      observationUnixMs.hashCode ^
      focalLength35Mm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolveOptionsDto &&
          runtimeType == other.runtimeType &&
          fovEstimateDeg == other.fovEstimateDeg &&
          fovMaxErrorDeg == other.fovMaxErrorDeg &&
          camera == other.camera &&
          attitudeHintWxyz == other.attitudeHintWxyz &&
          hintUncertaintyDeg == other.hintUncertaintyDeg &&
          strictHint == other.strictHint &&
          profile == other.profile &&
          retryAlternateProfile == other.retryAlternateProfile &&
          thorough == other.thorough &&
          matchThreshold == other.matchThreshold &&
          timeoutMs == other.timeoutMs &&
          observationUnixMs == other.observationUnixMs &&
          focalLength35Mm == other.focalLength35Mm;
}

class SolveOutcomeDto {
  final SolveStatusDto status;
  final SolvedGeometryDto? solution;
  final List<CentroidDto> centroids;
  final TimingDto timing;
  final bool extractionRetried;

  /// Star-shape diagnostic: median elongation of the brightest quarter (1.0 = round).
  /// **Relative, with no cross-device threshold**: it varies with pixel scale, PSF and
  /// exposure. Round stars on a telescope camera measure 1.3–1.4 and its untracked 3 s
  /// frames 1.8–1.9, while solvable phone frames span 1.13–2.51. Compare against a baseline
  /// from the same camera; never hard-code a threshold.
  final double? medianElongation;

  /// Observation time the solve used (Unix ms, UTC): the options', or for file entries the
  /// header's when it pins the zone (FITS DATE-OBS, EXIF with an offset). Pass it to
  /// `AnnotateOptionsDto.observationUnixMs` for the solar-system layer; null when neither
  /// gave one.
  final PlatformInt64? observationUnixMs;

  /// Where the photo was taken, for file entries whose EXIF has a GPS position. Pass it to
  /// `AnnotateOptionsDto.observer` with the time (the moon's parallax reaches 1° without
  /// it); null for frames and files without a position.
  final ObserverDto? observer;

  const SolveOutcomeDto({
    required this.status,
    this.solution,
    required this.centroids,
    required this.timing,
    required this.extractionRetried,
    this.medianElongation,
    this.observationUnixMs,
    this.observer,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      solution.hashCode ^
      centroids.hashCode ^
      timing.hashCode ^
      extractionRetried.hashCode ^
      medianElongation.hashCode ^
      observationUnixMs.hashCode ^
      observer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolveOutcomeDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          solution == other.solution &&
          centroids == other.centroids &&
          timing == other.timing &&
          extractionRetried == other.extractionRetried &&
          medianElongation == other.medianElongation &&
          observationUnixMs == other.observationUnixMs &&
          observer == other.observer;
}

enum SolveStatusDto { ok, noMatch, timeout, tooFew }

class SolvedGeometryDto {
  final F32Array4 quatIcrs2CamWxyz;
  final double raDeg;
  final double decDeg;
  final double rollDeg;
  final double fovDeg;
  final int numMatches;
  final double rmseArcsec;
  final double p90Arcsec;
  final double maxErrArcsec;
  final double prob;
  final WcsDto wcs;
  final List<MatchDto> matched;

  const SolvedGeometryDto({
    required this.quatIcrs2CamWxyz,
    required this.raDeg,
    required this.decDeg,
    required this.rollDeg,
    required this.fovDeg,
    required this.numMatches,
    required this.rmseArcsec,
    required this.p90Arcsec,
    required this.maxErrArcsec,
    required this.prob,
    required this.wcs,
    required this.matched,
  });

  @override
  int get hashCode =>
      quatIcrs2CamWxyz.hashCode ^
      raDeg.hashCode ^
      decDeg.hashCode ^
      rollDeg.hashCode ^
      fovDeg.hashCode ^
      numMatches.hashCode ^
      rmseArcsec.hashCode ^
      p90Arcsec.hashCode ^
      maxErrArcsec.hashCode ^
      prob.hashCode ^
      wcs.hashCode ^
      matched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolvedGeometryDto &&
          runtimeType == other.runtimeType &&
          quatIcrs2CamWxyz == other.quatIcrs2CamWxyz &&
          raDeg == other.raDeg &&
          decDeg == other.decDeg &&
          rollDeg == other.rollDeg &&
          fovDeg == other.fovDeg &&
          numMatches == other.numMatches &&
          rmseArcsec == other.rmseArcsec &&
          p90Arcsec == other.p90Arcsec &&
          maxErrArcsec == other.maxErrArcsec &&
          prob == other.prob &&
          wcs == other.wcs &&
          matched == other.matched;
}

class StarAnnotationDto {
  final double x;
  final double y;
  final double mag;
  final PlatformInt64 catalogId;

  const StarAnnotationDto({
    required this.x,
    required this.y,
    required this.mag,
    required this.catalogId,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ mag.hashCode ^ catalogId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarAnnotationDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          mag == other.mag &&
          catalogId == other.catalogId;
}

/// A registered tier (pool routing). Named as in the manifest, so a tier manager can match
/// installed and available tiers.
class TierInfoDto {
  final String name;
  final String path;
  final double minFovDeg;
  final double maxFovDeg;
  final BigInt numStars;
  final int numPatterns;
  final double starMaxMagnitude;

  const TierInfoDto({
    required this.name,
    required this.path,
    required this.minFovDeg,
    required this.maxFovDeg,
    required this.numStars,
    required this.numPatterns,
    required this.starMaxMagnitude,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      minFovDeg.hashCode ^
      maxFovDeg.hashCode ^
      numStars.hashCode ^
      numPatterns.hashCode ^
      starMaxMagnitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TierInfoDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          minFovDeg == other.minFovDeg &&
          maxFovDeg == other.maxFovDeg &&
          numStars == other.numStars &&
          numPatterns == other.numPatterns &&
          starMaxMagnitude == other.starMaxMagnitude;
}

class TimingDto {
  final double extractMs;
  final double solveMs;
  final double totalMs;

  const TimingDto({
    required this.extractMs,
    required this.solveMs,
    required this.totalMs,
  });

  @override
  int get hashCode => extractMs.hashCode ^ solveMs.hashCode ^ totalMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimingDto &&
          runtimeType == other.runtimeType &&
          extractMs == other.extractMs &&
          solveMs == other.solveMs &&
          totalMs == other.totalMs;
}

class WcsDto {
  final int width;
  final int height;

  /// [cd11, cd12, cd21, cd22]
  final F64Array4 cd;
  final double crvalRaDeg;
  final double crvalDecDeg;
  final double thetaRad;
  final CameraParamsDto camera;

  const WcsDto({
    required this.width,
    required this.height,
    required this.cd,
    required this.crvalRaDeg,
    required this.crvalDecDeg,
    required this.thetaRad,
    required this.camera,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      cd.hashCode ^
      crvalRaDeg.hashCode ^
      crvalDecDeg.hashCode ^
      thetaRad.hashCode ^
      camera.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WcsDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          cd == other.cd &&
          crvalRaDeg == other.crvalRaDeg &&
          crvalDecDeg == other.crvalDecDeg &&
          thetaRad == other.thetaRad &&
          camera == other.camera;
}
