// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `batch`

/// Sky → pixel: interleaved `[ra0, dec0, ra1, dec1, …]` (degrees) to interleaved top-left
/// pixels. A point the lens model cannot place (behind the camera, or beyond 1.2× the
/// frame's corner distance, where the distortion polynomial folds points back in) comes back
/// as NaN, NaN.
Float64List wcsSkyToPixels({
  required WcsDto wcs,
  required List<double> radec,
}) => RustLib.instance.api.crateApiWcsWcsSkyToPixels(wcs: wcs, radec: radec);

/// Pixel → sky: interleaved top-left pixels to interleaved `[ra, dec]` (degrees); NaN, NaN for
/// pixels more than a quarter frame outside the image.
Float64List wcsPixelsToSky({
  required WcsDto wcs,
  required List<double> pixels,
}) => RustLib.instance.api.crateApiWcsWcsPixelsToSky(wcs: wcs, pixels: pixels);
